export const branchData = [
  {
    id: 1,
    code: "BR001",
    name: "Head Office",
    location: "New Delhi",
    address: "Plot 12, Industrial Area, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110020",
    phone: "+91 98765 43210",
    email: "headoffice@company.com",
    manager: "Rahul Sharma",
    employeeCount: 85,
    status: "Active",
    createdOn: "2026-01-10",
  },
  {
    id: 2,
    code: "BR002",
    name: "Mumbai Branch",
    location: "Mumbai",
    address: "Andheri East, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400069",
    phone: "+91 98765 43211",
    email: "mumbai@company.com",
    manager: "Amit Verma",
    employeeCount: 52,
    status: "Active",
    createdOn: "2026-01-15",
  },
  {
    id: 3,
    code: "BR003",
    name: "Bangalore Branch",
    location: "Bangalore",
    address: "Whitefield Main Road, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560066",
    phone: "+91 98765 43212",
    email: "bangalore@company.com",
    manager: "Priya Singh",
    employeeCount: 64,
    status: "Active",
    createdOn: "2026-02-05",
  },
  {
    id: 4,
    code: "BR004",
    name: "Hyderabad Branch",
    location: "Hyderabad",
    address: "Hitech City, Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500081",
    phone: "+91 98765 43213",
    email: "hyderabad@company.com",
    manager: "Arjun Kumar",
    employeeCount: 43,
    status: "Active",
    createdOn: "2026-02-18",
  },
  {
    id: 5,
    code: "BR005",
    name: "Pune Branch",
    location: "Pune",
    address: "Hinjewadi Phase 1, Pune",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411057",
    phone: "+91 98765 43214",
    email: "pune@company.com",
    manager: "Neha Gupta",
    employeeCount: 37,
    status: "Inactive",
    createdOn: "2026-03-02",
  },
  {
    id: 6,
    code: "BR006",
    name: "Chennai Branch",
    location: "Chennai",
    address: "Guindy Industrial Estate, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600032",
    phone: "+91 98765 43215",
    email: "chennai@company.com",
    manager: "Vikash Yadav",
    employeeCount: 29,
    status: "Active",
    createdOn: "2026-03-12",
  },
  {
    id: 7,
    code: "BR007",
    name: "Kolkata Branch",
    location: "Kolkata",
    address: "Salt Lake Sector V, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700091",
    phone: "+91 98765 43216",
    email: "kolkata@company.com",
    manager: "Sneha Patel",
    employeeCount: 25,
    status: "Active",
    createdOn: "2026-04-01",
  },
  {
    id: 8,
    code: "BR008",
    name: "Ahmedabad Branch",
    location: "Ahmedabad",
    address: "SG Highway, Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380054",
    phone: "+91 98765 43217",
    email: "ahmedabad@company.com",
    manager: "Rohit Das",
    employeeCount: 31,
    status: "Inactive",
    createdOn: "2026-04-15",
  },
  {
    id: 9,
    code: "BR009",
    name: "Noida Branch",
    location: "Noida",
    address: "Sector 62, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201309",
    phone: "+91 98765 43218",
    email: "noida@company.com",
    manager: "Aman Verma",
    employeeCount: 48,
    status: "Active",
    createdOn: "2026-05-10",
  },
  {
    id: 10,
    code: "BR010",
    name: "Lucknow Branch",
    location: "Lucknow",
    address: "Gomti Nagar, Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226010",
    phone: "+91 98765 43219",
    email: "lucknow@company.com",
    manager: "Pooja Sharma",
    employeeCount: 22,
    status: "Active",
    createdOn: "2026-06-01",
  },
];

export const branchStatusOptions = [
  {
    value: "",
    label: "All Status",
  },
  {
    value: "Active",
    label: "Active",
  },
  {
    value: "Inactive",
    label: "Inactive",
  },
];

export const stateOptions = [
  {
    value: "",
    label: "All States",
  },
  {
    value: "Delhi",
    label: "Delhi",
  },
  {
    value: "Maharashtra",
    label: "Maharashtra",
  },
  {
    value: "Karnataka",
    label: "Karnataka",
  },
  {
    value: "Telangana",
    label: "Telangana",
  },
  {
    value: "Tamil Nadu",
    label: "Tamil Nadu",
  },
  {
    value: "West Bengal",
    label: "West Bengal",
  },
  {
    value: "Gujarat",
    label: "Gujarat",
  },
  {
    value: "Uttar Pradesh",
    label: "Uttar Pradesh",
  },
];