const leaveData = [
  {
    id: 1,
    employeeId: "EMP-1024",
    employeeName: "Rahul Sharma",
    department: "Development",
    leaveType: "Casual Leave",
    fromDate: "15 Sep 2026",
    toDate: "16 Sep 2026",
    days: 2,
    appliedOn: "12 Sep 2026",
    reason: "Personal work",
    status: "Pending",
    initials: "RS",
  },
  {
    id: 2,
    employeeId: "EMP-1023",
    employeeName: "Priya Singh",
    department: "HR",
    leaveType: "Sick Leave",
    fromDate: "14 Sep 2026",
    toDate: "14 Sep 2026",
    days: 1,
    appliedOn: "13 Sep 2026",
    reason: "Not feeling well",
    status: "Approved",
    initials: "PS",
  },
  {
    id: 3,
    employeeId: "EMP-1022",
    employeeName: "Aman Verma",
    department: "Finance",
    leaveType: "Casual Leave",
    fromDate: "18 Sep 2026",
    toDate: "19 Sep 2026",
    days: 2,
    appliedOn: "10 Sep 2026",
    reason: "Family function",
    status: "Pending",
    initials: "AV",
  },
  {
    id: 4,
    employeeId: "EMP-1021",
    employeeName: "Neha Gupta",
    department: "Marketing",
    leaveType: "Earned Leave",
    fromDate: "21 Sep 2026",
    toDate: "24 Sep 2026",
    days: 4,
    appliedOn: "08 Sep 2026",
    reason: "Vacation",
    status: "Approved",
    initials: "NG",
  },
  {
    id: 5,
    employeeId: "EMP-1020",
    employeeName: "Arjun Kumar",
    department: "Operations",
    leaveType: "Casual Leave",
    fromDate: "11 Sep 2026",
    toDate: "11 Sep 2026",
    days: 1,
    appliedOn: "09 Sep 2026",
    reason: "Personal work",
    status: "Rejected",
    initials: "AK",
  },
  {
    id: 6,
    employeeId: "EMP-1019",
    employeeName: "Sneha Patel",
    department: "Development",
    leaveType: "Sick Leave",
    fromDate: "09 Sep 2026",
    toDate: "10 Sep 2026",
    days: 2,
    appliedOn: "08 Sep 2026",
    reason: "Medical appointment",
    status: "Approved",
    initials: "SP",
  },
  {
    id: 7,
    employeeId: "EMP-1018",
    employeeName: "Vikash Yadav",
    department: "Sales",
    leaveType: "Earned Leave",
    fromDate: "28 Sep 2026",
    toDate: "30 Sep 2026",
    days: 3,
    appliedOn: "05 Sep 2026",
    reason: "Personal vacation",
    status: "Pending",
    initials: "VY",
  },
  {
    id: 8,
    employeeId: "EMP-1017",
    employeeName: "Anjali Mehta",
    department: "Finance",
    leaveType: "Casual Leave",
    fromDate: "07 Sep 2026",
    toDate: "07 Sep 2026",
    days: 1,
    appliedOn: "06 Sep 2026",
    reason: "Personal work",
    status: "Approved",
    initials: "AM",
  },
  {
    id: 9,
    employeeId: "EMP-1016",
    employeeName: "Rohit Das",
    department: "Operations",
    leaveType: "Sick Leave",
    fromDate: "03 Sep 2026",
    toDate: "04 Sep 2026",
    days: 2,
    appliedOn: "02 Sep 2026",
    reason: "Health issue",
    status: "Approved",
    initials: "RD",
  },
  {
    id: 10,
    employeeId: "EMP-1015",
    employeeName: "Pooja Sharma",
    department: "HR",
    leaveType: "Casual Leave",
    fromDate: "22 Sep 2026",
    toDate: "22 Sep 2026",
    days: 1,
    appliedOn: "15 Sep 2026",
    reason: "Personal work",
    status: "Pending",
    initials: "PS",
  },
];

export const departmentOptions = [
  "All Departments",
  "Development",
  "HR",
  "Finance",
  "Marketing",
  "Operations",
  "Sales",
];

export const leaveTypeOptions = [
  "All Leave Types",
  "Casual Leave",
  "Sick Leave",
  "Earned Leave",
  "Unpaid Leave",
  "Maternity Leave",
  "Paternity Leave",
];

export const leaveStatusOptions = [
  "All Status",
  "Pending",
  "Approved",
  "Rejected",
];



export default leaveData;