export const leaveTypeData = [
  {
    id: 1,
    code: "CL",
    name: "Casual Leave",
    description: "Leave for personal and short-term requirements.",
    allocation: 12,
    carryForward: false,
    maxCarryForward: 0,
    encashable: false,
    requiresApproval: true,
    halfDayAllowed: true,
    attachmentRequired: false,
    applicableTo: "All Employees",
    status: "Active",
  },
  {
    id: 2,
    code: "SL",
    name: "Sick Leave",
    description: "Leave available for illness or medical reasons.",
    allocation: 12,
    carryForward: true,
    maxCarryForward: 6,
    encashable: false,
    requiresApproval: true,
    halfDayAllowed: true,
    attachmentRequired: true,
    applicableTo: "All Employees",
    status: "Active",
  },
  {
    id: 3,
    code: "EL",
    name: "Earned Leave",
    description: "Leave earned based on employee service and attendance.",
    allocation: 18,
    carryForward: true,
    maxCarryForward: 30,
    encashable: true,
    requiresApproval: true,
    halfDayAllowed: false,
    attachmentRequired: false,
    applicableTo: "All Employees",
    status: "Active",
  },
  {
    id: 4,
    code: "UL",
    name: "Unpaid Leave",
    description: "Leave taken without salary deduction protection.",
    allocation: 0,
    carryForward: false,
    maxCarryForward: 0,
    encashable: false,
    requiresApproval: true,
    halfDayAllowed: true,
    attachmentRequired: false,
    applicableTo: "All Employees",
    status: "Active",
  },
  {
    id: 5,
    code: "ML",
    name: "Maternity Leave",
    description: "Leave provided for eligible female employees.",
    allocation: 90,
    carryForward: false,
    maxCarryForward: 0,
    encashable: false,
    requiresApproval: true,
    halfDayAllowed: false,
    attachmentRequired: true,
    applicableTo: "Female Employees",
    status: "Active",
  },
  {
    id: 6,
    code: "PL",
    name: "Paternity Leave",
    description: "Leave provided to eligible employees after childbirth.",
    allocation: 15,
    carryForward: false,
    maxCarryForward: 0,
    encashable: false,
    requiresApproval: true,
    halfDayAllowed: false,
    attachmentRequired: true,
    applicableTo: "Male Employees",
    status: "Active",
  },
  {
    id: 7,
    code: "CO",
    name: "Compensatory Off",
    description: "Leave granted against approved extra working days.",
    allocation: 0,
    carryForward: true,
    maxCarryForward: 5,
    encashable: false,
    requiresApproval: true,
    halfDayAllowed: true,
    attachmentRequired: false,
    applicableTo: "All Employees",
    status: "Inactive",
  },
];

export const applicableOptions = [
  "All Employees",
  "Male Employees",
  "Female Employees",
];

export const statusOptions = [
  "All Status",
  "Active",
  "Inactive",
];