// src/pages/Masters/Shift/ShiftData.js

export const shiftData = [
  {
    id: 1,
    code: "GEN",
    name: "General Shift",
    description: "Standard office working shift",
    startTime: "09:00",
    endTime: "18:00",
    breakStart: "13:00",
    breakEnd: "14:00",
    workingHours: 8,
    gracePeriod: 15,
    employeeCount: 42,
    status: "Active",
    createdOn: "2026-01-10",
  },
  {
    id: 2,
    code: "MOR",
    name: "Morning Shift",
    description: "Early morning operational shift",
    startTime: "06:00",
    endTime: "15:00",
    breakStart: "10:00",
    breakEnd: "11:00",
    workingHours: 8,
    gracePeriod: 10,
    employeeCount: 18,
    status: "Active",
    createdOn: "2026-01-12",
  },
  {
    id: 3,
    code: "EVE",
    name: "Evening Shift",
    description: "Evening operational shift",
    startTime: "14:00",
    endTime: "23:00",
    breakStart: "18:00",
    breakEnd: "19:00",
    workingHours: 8,
    gracePeriod: 10,
    employeeCount: 15,
    status: "Active",
    createdOn: "2026-01-15",
  },
  {
    id: 4,
    code: "NIGHT",
    name: "Night Shift",
    description: "Night working shift for operations",
    startTime: "22:00",
    endTime: "07:00",
    breakStart: "02:00",
    breakEnd: "03:00",
    workingHours: 8,
    gracePeriod: 15,
    employeeCount: 11,
    status: "Active",
    createdOn: "2026-01-18",
  },
  {
    id: 5,
    code: "FLEX",
    name: "Flexible Shift",
    description: "Flexible working hours for eligible employees",
    startTime: "10:00",
    endTime: "19:00",
    breakStart: "14:00",
    breakEnd: "15:00",
    workingHours: 8,
    gracePeriod: 20,
    employeeCount: 8,
    status: "Active",
    createdOn: "2026-02-01",
  },
  {
    id: 6,
    code: "GEN2",
    name: "General Shift - 2",
    description: "Alternate general office shift",
    startTime: "08:30",
    endTime: "17:30",
    breakStart: "13:00",
    breakEnd: "14:00",
    workingHours: 8,
    gracePeriod: 15,
    employeeCount: 23,
    status: "Active",
    createdOn: "2026-02-05",
  },
  {
    id: 7,
    code: "OPS",
    name: "Operations Shift",
    description: "Shift configured for operations team",
    startTime: "07:00",
    endTime: "16:00",
    breakStart: "11:00",
    breakEnd: "12:00",
    workingHours: 8,
    gracePeriod: 10,
    employeeCount: 14,
    status: "Active",
    createdOn: "2026-02-12",
  },
  {
    id: 8,
    code: "SUP",
    name: "Support Shift",
    description: "Customer and technical support shift",
    startTime: "11:00",
    endTime: "20:00",
    breakStart: "15:00",
    breakEnd: "16:00",
    workingHours: 8,
    gracePeriod: 15,
    employeeCount: 9,
    status: "Active",
    createdOn: "2026-02-20",
  },
  {
    id: 9,
    code: "WEEK",
    name: "Weekend Shift",
    description: "Special weekend working shift",
    startTime: "09:00",
    endTime: "18:00",
    breakStart: "13:00",
    breakEnd: "14:00",
    workingHours: 8,
    gracePeriod: 15,
    employeeCount: 6,
    status: "Inactive",
    createdOn: "2026-03-02",
  },
  {
    id: 10,
    code: "PART",
    name: "Part Time Shift",
    description: "Part-time employee working shift",
    startTime: "10:00",
    endTime: "15:00",
    breakStart: "12:30",
    breakEnd: "13:00",
    workingHours: 4.5,
    gracePeriod: 10,
    employeeCount: 5,
    status: "Active",
    createdOn: "2026-03-08",
  },
];

export const shiftStatusOptions = [
  {
    value: "All",
    label: "All Status",
  },
  {
    value: "Active",
    label: "Active",
  },
  {
    value: "Inactive",
    label: "Inactive",
  },
];