export const employeeListData = [
  {
    id: 1,
    employeeId: "EMP-1024",
    name: "Rahul Sharma",
    email: "rahul.sharma@company.com",
    phone: "+91 9876543210",
    department: "Development",
    designation: "Software Engineer",
    joiningDate: "12 Sep 2026",
    status: "Active",
    initials: "RS",
  },

  {
    id: 2,
    employeeId: "EMP-1023",
    name: "Priya Singh",
    email: "priya.singh@company.com",
    phone: "+91 9876543211",
    department: "Human Resources",
    designation: "HR Executive",
    joiningDate: "10 Sep 2026",
    status: "Active",
    initials: "PS",
  },

  {
    id: 3,
    employeeId: "EMP-1022",
    name: "Aman Verma",
    email: "aman.verma@company.com",
    phone: "+91 9876543212",
    department: "Finance",
    designation: "Accountant",
    joiningDate: "08 Sep 2026",
    status: "Active",
    initials: "AV",
  },

  {
    id: 4,
    employeeId: "EMP-1021",
    name: "Neha Gupta",
    email: "neha.gupta@company.com",
    phone: "+91 9876543213",
    department: "Marketing",
    designation: "Marketing Executive",
    joiningDate: "06 Sep 2026",
    status: "Active",
    initials: "NG",
  },

  {
    id: 5,
    employeeId: "EMP-1020",
    name: "Arjun Kumar",
    email: "arjun.kumar@company.com",
    phone: "+91 9876543214",
    department: "Operations",
    designation: "Operations Manager",
    joiningDate: "04 Sep 2026",
    status: "Active",
    initials: "AK",
  },

  {
    id: 6,
    employeeId: "EMP-1019",
    name: "Sneha Patel",
    email: "sneha.patel@company.com",
    phone: "+91 9876543215",
    department: "Development",
    designation: "React Native Developer",
    joiningDate: "02 Sep 2026",
    status: "Active",
    initials: "SP",
  },

  {
    id: 7,
    employeeId: "EMP-1018",
    name: "Vikash Yadav",
    email: "vikash.yadav@company.com",
    phone: "+91 9876543216",
    department: "Sales",
    designation: "Sales Executive",
    joiningDate: "30 Aug 2026",
    status: "On Leave",
    initials: "VY",
  },

  {
    id: 8,
    employeeId: "EMP-1017",
    name: "Anjali Mehta",
    email: "anjali.mehta@company.com",
    phone: "+91 9876543217",
    department: "Finance",
    designation: "Senior Accountant",
    joiningDate: "28 Aug 2026",
    status: "Active",
    initials: "AM",
  },

  {
    id: 9,
    employeeId: "EMP-1016",
    name: "Rohit Das",
    email: "rohit.das@company.com",
    phone: "+91 9876543218",
    department: "Operations",
    designation: "Operations Executive",
    joiningDate: "25 Aug 2026",
    status: "Inactive",
    initials: "RD",
  },

  {
    id: 10,
    employeeId: "EMP-1015",
    name: "Pooja Sharma",
    email: "pooja.sharma@company.com",
    phone: "+91 9876543219",
    department: "Human Resources",
    designation: "HR Manager",
    joiningDate: "22 Aug 2026",
    status: "Active",
    initials: "PS",
  },
];

export const departmentOptions = [
  "All Departments",
  "Development",
  "Human Resources",
  "Finance",
  "Marketing",
  "Operations",
  "Sales",
];

export const statusOptions = [
  "All Status",
  "Active",
  "Inactive",
  "On Leave",
];