export const attendanceData = [
  {
    id: 1,
    employeeId: "EMP-1024",
    name: "Rahul Sharma",
    department: "Development",
    designation: "Software Engineer",
    date: "15 Sep 2026",
    checkIn: "09:02 AM",
    checkOut: "06:08 PM",
    workHours: "9h 06m",
    status: "Present",
    initials: "RS",
  },
  {
    id: 2,
    employeeId: "EMP-1023",
    name: "Priya Singh",
    department: "Human Resources",
    designation: "HR Executive",
    date: "15 Sep 2026",
    checkIn: "08:55 AM",
    checkOut: "06:02 PM",
    workHours: "9h 07m",
    status: "Present",
    initials: "PS",
  },
  {
    id: 3,
    employeeId: "EMP-1022",
    name: "Aman Verma",
    department: "Finance",
    designation: "Accountant",
    date: "15 Sep 2026",
    checkIn: "09:18 AM",
    checkOut: "06:05 PM",
    workHours: "8h 47m",
    status: "Late",
    initials: "AV",
  },
  {
    id: 4,
    employeeId: "EMP-1021",
    name: "Neha Gupta",
    department: "Marketing",
    designation: "Marketing Executive",
    date: "15 Sep 2026",
    checkIn: "09:01 AM",
    checkOut: "05:58 PM",
    workHours: "8h 57m",
    status: "Present",
    initials: "NG",
  },
  {
    id: 5,
    employeeId: "EMP-1020",
    name: "Arjun Kumar",
    department: "Operations",
    designation: "Operations Manager",
    date: "15 Sep 2026",
    checkIn: "-",
    checkOut: "-",
    workHours: "-",
    status: "Absent",
    initials: "AK",
  },
  {
    id: 6,
    employeeId: "EMP-1019",
    name: "Sneha Patel",
    department: "Development",
    designation: "React Native Developer",
    date: "15 Sep 2026",
    checkIn: "08:48 AM",
    checkOut: "06:15 PM",
    workHours: "9h 27m",
    status: "Present",
    initials: "SP",
  },
  {
    id: 7,
    employeeId: "EMP-1018",
    name: "Vikash Yadav",
    department: "Sales",
    designation: "Sales Executive",
    date: "15 Sep 2026",
    checkIn: "-",
    checkOut: "-",
    workHours: "-",
    status: "On Leave",
    initials: "VY",
  },
  {
    id: 8,
    employeeId: "EMP-1017",
    name: "Anjali Mehta",
    department: "Finance",
    designation: "Senior Accountant",
    date: "15 Sep 2026",
    checkIn: "09:05 AM",
    checkOut: "06:00 PM",
    workHours: "8h 55m",
    status: "Present",
    initials: "AM",
  },
  {
    id: 9,
    employeeId: "EMP-1016",
    name: "Rohit Das",
    department: "Operations",
    designation: "Operations Executive",
    date: "15 Sep 2026",
    checkIn: "09:42 AM",
    checkOut: "06:10 PM",
    workHours: "8h 28m",
    status: "Late",
    initials: "RD",
  },
  {
    id: 10,
    employeeId: "EMP-1015",
    name: "Pooja Sharma",
    department: "Human Resources",
    designation: "HR Manager",
    date: "15 Sep 2026",
    checkIn: "08:52 AM",
    checkOut: "06:04 PM",
    workHours: "9h 12m",
    status: "Present",
    initials: "PS",
  },
];

export const departmentOptions = [
  "All Departments",
  "Development",
  "Human Resources",
  "Finance",
  "Marketing",
  "Operations",
  "Sales",
];

export const statusOptions = [
  "All Status",
  "Present",
  "Absent",
  "Late",
  "On Leave",
];