export const bankData = [
  {
    id: 1,
    code: "HDFC001",
    name: "HDFC Bank",
    branchName: "Connaught Place",
    branchCode: "HDFC0001234",
    ifscCode: "HDFC0001234",
    address: "A-12, Connaught Place",
    city: "Delhi",
    state: "Delhi",
    contactNumber: "011-45678901",
    email: "cp.branch@hdfcbank.com",
    employeeCount: 18,
    status: "Active",
    createdOn: "2026-01-05",
  },
  {
    id: 2,
    code: "SBI001",
    name: "State Bank of India",
    branchName: "Sector 18",
    branchCode: "SBIN0004567",
    ifscCode: "SBIN0004567",
    address: "B-18, Sector 18",
    city: "Noida",
    state: "Uttar Pradesh",
    contactNumber: "0120-4567890",
    email: "sector18@sbi.co.in",
    employeeCount: 24,
    status: "Active",
    createdOn: "2026-01-08",
  },
  {
    id: 3,
    code: "ICICI001",
    name: "ICICI Bank",
    branchName: "Whitefield",
    branchCode: "ICIC0007890",
    ifscCode: "ICIC0007890",
    address: "ITPL Main Road, Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    contactNumber: "080-45678912",
    email: "whitefield@icicibank.com",
    employeeCount: 15,
    status: "Active",
    createdOn: "2026-01-12",
  },
  {
    id: 4,
    code: "AXIS001",
    name: "Axis Bank",
    branchName: "Andheri East",
    branchCode: "UTIB0002345",
    ifscCode: "UTIB0002345",
    address: "Andheri East Main Road",
    city: "Mumbai",
    state: "Maharashtra",
    contactNumber: "022-45678912",
    email: "andherieast@axisbank.com",
    employeeCount: 12,
    status: "Active",
    createdOn: "2026-01-18",
  },
  {
    id: 5,
    code: "KOTAK001",
    name: "Kotak Mahindra Bank",
    branchName: "Banjara Hills",
    branchCode: "KKBK0003456",
    ifscCode: "KKBK0003456",
    address: "Road No. 12, Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    contactNumber: "040-45678901",
    email: "banjarahills@kotak.com",
    employeeCount: 9,
    status: "Active",
    createdOn: "2026-02-02",
  },
  {
    id: 6,
    code: "PNB001",
    name: "Punjab National Bank",
    branchName: "Salt Lake",
    branchCode: "PUNB0005678",
    ifscCode: "PUNB0005678",
    address: "Sector V, Salt Lake",
    city: "Kolkata",
    state: "West Bengal",
    contactNumber: "033-45678923",
    email: "saltlake@pnb.co.in",
    employeeCount: 11,
    status: "Active",
    createdOn: "2026-02-08",
  },
  {
    id: 7,
    code: "BOB001",
    name: "Bank of Baroda",
    branchName: "Viman Nagar",
    branchCode: "BARB0006789",
    ifscCode: "BARB0006789",
    address: "Viman Nagar Main Road",
    city: "Pune",
    state: "Maharashtra",
    contactNumber: "020-45678912",
    email: "vimannagar@bankofbaroda.com",
    employeeCount: 8,
    status: "Active",
    createdOn: "2026-02-15",
  },
  {
    id: 8,
    code: "INDUS001",
    name: "IndusInd Bank",
    branchName: "Gurugram Sector 44",
    branchCode: "INDB0007891",
    ifscCode: "INDB0007891",
    address: "Sector 44, Gurugram",
    city: "Gurugram",
    state: "Haryana",
    contactNumber: "0124-4567890",
    email: "sector44@indusind.com",
    employeeCount: 7,
    status: "Active",
    createdOn: "2026-02-21",
  },
  {
    id: 9,
    code: "CAN001",
    name: "Canara Bank",
    branchName: "Ashok Nagar",
    branchCode: "CNRB0008912",
    ifscCode: "CNRB0008912",
    address: "Ashok Nagar Main Road",
    city: "Chennai",
    state: "Tamil Nadu",
    contactNumber: "044-45678923",
    email: "ashoknagar@canarabank.com",
    employeeCount: 5,
    status: "Inactive",
    createdOn: "2026-03-01",
  },
  {
    id: 10,
    code: "YES001",
    name: "Yes Bank",
    branchName: "Hinjewadi",
    branchCode: "YESB0009123",
    ifscCode: "YESB0009123",
    address: "Phase 1, Hinjewadi",
    city: "Pune",
    state: "Maharashtra",
    contactNumber: "020-45678934",
    email: "hinjewadi@yesbank.in",
    employeeCount: 6,
    status: "Active",
    createdOn: "2026-03-10",
  },
];

export const bankStatusOptions = [
  {
    value: "All",
    label: "All Status",
  },
  {
    value: "Active",
    label: "Active",
  },
  {
    value: "Inactive",
    label: "Inactive",
  },
];

export const bankCityOptions = [
  {
    value: "All",
    label: "All Cities",
  },
  {
    value: "Delhi",
    label: "Delhi",
  },
  {
    value: "Noida",
    label: "Noida",
  },
  {
    value: "Bengaluru",
    label: "Bengaluru",
  },
  {
    value: "Mumbai",
    label: "Mumbai",
  },
  {
    value: "Hyderabad",
    label: "Hyderabad",
  },
  {
    value: "Kolkata",
    label: "Kolkata",
  },
  {
    value: "Pune",
    label: "Pune",
  },
  {
    value: "Gurugram",
    label: "Gurugram",
  },
  {
    value: "Chennai",
    label: "Chennai",
  },
];